### ISSUE TITLE
ERROR: Try to use tldream besides Automatic1111 installation

### ISSUE THREAD

**Issue by Woisek** [Sanster/tldream#1]
After install of tldream I got some errors regarding xformers (PyTorch and Python). My question is: Can it still be run somehow without risking to cripple the functional WebUI installation?

I:\Super SD 2.0\tldream>tldream --model "I:\stable_diffusion_shared\models\Stable-diffusion\SD v1.5\v1-5-pruned-emaonly_(3.97GB).ckpt" --listen localhost --no-nsfw-filter --local-files-only
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu)
    Python  3.10.9 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ F:\Programme\Python310\lib\runpy.py:196 in _run_module_as_main                                   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ F:\Programme\Python310\lib\runpy.py:86 in _run_code                                              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from tldream import entry_point                                                              │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(entry_point())                                                                  │
│   8                                                                                              │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\tldream\__init__.py:63 in entry_point                   │
│                                                                                                  │
│   60                                                                                             │
│   61                                                                                             │
│   62 def entry_point():                                                                          │
│ ❱ 63 │   typer_app()                                                                             │
│   64                                                                                             │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\main.py:328 in __call__                           │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\main.py:311 in __call__                           │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\click\core.py:829 in __call__                           │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\core.py:716 in main                               │
│                                                                                                  │
│ F:\Programme\Python310\lib\site-packages\typer\core.py:190 in _main                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'click.utils' has no attribute '_expand_args'

I:\Super SD 2.0\tldream>

Thanks for this great little tool. 👍

**Comment by Sanster** [comment]
By default, tldream installs the CPU version of Torch. You can try installing the GPU version of torch first:

```bash
# In order to use the GPU, install cuda version of pytorch first.
pip install torch==1.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
pip install tldream
tldream --model runwayml/stable-diffusion-v1-5 --device cuda
```


BTW: I made a [windows 1-click installer](https://github.com/Sanster/tldream/blob/tldream/scripts/README.md), Please feel free to check if you need it.

**Comment by Woisek** [comment]
But will the torch version then not conflict with the already installed Automatic1111 installation ... ?

**Comment by Sanster** [comment]
Should not be, the same version is used here

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2/launch.py#L240

**Comment by Sanster** [comment]
But I am not sure whether another package will have a conflict or not...
