### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by runmax4** [Sanster/tldream#2]
I have paid but nothing can download, the link is go back to intro page?
my email: runmax4@gmail.com
thanks

**Comment by Sanster** [comment]
Sorry about this, I have resent the email, it should work this time. Thank you for your support! If you encounter any problems, please feel free to ask here.

**Comment by runmax4** [comment]
Sorry, but the mail's link back to the order page, not to the download link.
Thanks,

**Comment by Sanster** [comment]
Yes, it is expected to jump to the order page. There should be a download button on the order page. Do you have it on your page?
<img width="508" alt="截屏2023-03-14 22 14 51" src="https://user-images.githubusercontent.com/3998421/225029245-42a68427-f2be-47b6-b7cd-77472b033de5.png">

**Comment by runmax4** [comment]
Sorry, no that link go back to https://github.com/Sanster/tldream/blob/tldream/scripts/README.md

**Comment by Sanster** [comment]
😱Maybe there is an issue with my payment supplier. I have sent you the download link from my personal email (cwq1913@gmail.com), please check it.

**Comment by Sanster** [comment]
😱 Maybe there is some issue with my payment provider. I sent the link using my personal email (cwq1913@gmail.com) - it's the second email, as the link in the first one was no longer valid.
